version: '3'
services:
  ubuntu1:
    build: .
    ports:
      - "2201:22"
  ubuntu2:
    build: .
    ports:
      - "2202:22"
  ubuntu3:
    build: .
    ports:
      - "2203:22"
  ubuntu4:
    build: .
    ports:
      - "2204:22"
  ubuntu5:
    build: .
    ports:
      - "2205:22"
